"""Initial SafeBite schema

Revision ID: ac3afc0e6205
Revises:
Create Date: 2026-07-10 13:53:20.534615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "ac3afc0e6205"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "customer", "owner", "inspector", "admin", name="userrole"
            ),
            nullable=False,
        ),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table(
        "restaurants",
        sa.Column("restaurant_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("contact_number", sa.String(length=20), nullable=False),
        sa.Column(
            "safety_score", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("restaurant_id"),
    )
    op.create_table(
        "certificates",
        sa.Column("certificate_id", sa.UUID(), nullable=False),
        sa.Column("restaurant_id", sa.UUID(), nullable=False),
        sa.Column(
            "certificate_type",
            sa.Enum(
                "FSSAI",
                "FIRE_SAFETY",
                "HEALTH",
                "HYGIENE",
                "OTHER",
                name="certificatetype",
            ),
            nullable=False,
        ),
        sa.Column("certificate_number", sa.String(length=100), nullable=False),
        sa.Column("issuing_authority", sa.String(length=200), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "EXPIRED",
                "REJECTED",
                name="certificatestatus",
            ),
            nullable=False,
        ),
        sa.Column("document_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.restaurant_id"],
        ),
        sa.PrimaryKeyConstraint("certificate_id"),
    )
    op.create_table(
        "complaints",
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("restaurant_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "UNDER_INVESTIGATION",
                "RESOLVED",
                name="complaintstatus",
            ),
            nullable=False,
        ),
        sa.Column("evidence_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.restaurant_id"],
        ),
        sa.PrimaryKeyConstraint("complaint_id"),
    )
    op.create_table(
        "inspections",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("restaurant_id", sa.UUID(), nullable=False),
        sa.Column("inspector_id", sa.UUID(), nullable=False),
        sa.Column("inspection_date", sa.Date(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["inspector_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.restaurant_id"],
        ),
        sa.PrimaryKeyConstraint("inspection_id"),
    )
    op.create_table(
        "safety_scores",
        sa.Column("score_id", sa.UUID(), nullable=False),
        sa.Column("restaurant_id", sa.UUID(), nullable=False),
        sa.Column(
            "final_score", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "inspection_weight",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "complaint_weight",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "certificate_weight",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "feedback_weight", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.restaurant_id"],
        ),
        sa.PrimaryKeyConstraint("score_id"),
        sa.UniqueConstraint("restaurant_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("safety_scores")
    op.drop_table("inspections")
    op.drop_table("complaints")
    op.drop_table("certificates")
    op.drop_table("restaurants")
    # op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
