# Certificate Settings
CERTIFICATE_EXPIRY_WARNING_DAYS = 30

# Inspection Settings
INSPECTION_OVERDUE_DAYS = 90

# Risk Thresholds
HIGH_RISK_SAFETY_SCORE = 50
CRITICAL_RISK_SAFETY_SCORE = 40

# Dashboard Settings
DEFAULT_RECENT_LIMIT = 10
TOP_RESTAURANTS_LIMIT = 10
TOP_INSPECTORS_LIMIT = 10
